version: '3.7'
services:
  jenkins:
    image: "jenkins/jenkins:2.150.1-alpine"
    container_name: jenkins
    restart: "no"
    ports:
      - 8081:8080
    volumes:
      - ./config:/var/jenkins_home
